// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/authserver/authserver.proto

package authserver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// CreateTokenRequest represents the request of CreateToken.
type CreateTokenRequest struct {
	// user is the username which want to be authenticate.
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// password is the credential of given user.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// orig_host is the hostname for which JWT token is valid.
	OrigHost             string   `protobuf:"bytes,3,opt,name=orig_host,json=origHost,proto3" json:"orig_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTokenRequest) Reset()         { *m = CreateTokenRequest{} }
func (m *CreateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTokenRequest) ProtoMessage()    {}
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b970e5b30bc31cb8, []int{0}
}

func (m *CreateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenRequest.Unmarshal(m, b)
}
func (m *CreateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenRequest.Merge(m, src)
}
func (m *CreateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTokenRequest.Size(m)
}
func (m *CreateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenRequest proto.InternalMessageInfo

func (m *CreateTokenRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *CreateTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateTokenRequest) GetOrigHost() string {
	if m != nil {
		return m.OrigHost
	}
	return ""
}

//*
// Token represents the response of CreateToken.
type Token struct {
	// token is the JWT token.
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_b970e5b30bc31cb8, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//*
// ValidateTokenRequest represents the request of ValidateToken.
type ValidateTokenRequest struct {
	// token is the JWT token.
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenRequest) Reset()         { *m = ValidateTokenRequest{} }
func (m *ValidateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenRequest) ProtoMessage()    {}
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b970e5b30bc31cb8, []int{2}
}

func (m *ValidateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenRequest.Unmarshal(m, b)
}
func (m *ValidateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenRequest.Marshal(b, m, deterministic)
}
func (m *ValidateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenRequest.Merge(m, src)
}
func (m *ValidateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenRequest.Size(m)
}
func (m *ValidateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenRequest proto.InternalMessageInfo

func (m *ValidateTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//*
// ValidateTokenResponse represents the response of ValidateToken.
type ValidateTokenResponse struct {
	// valid represents whether given token is valid or not.
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenResponse) Reset()         { *m = ValidateTokenResponse{} }
func (m *ValidateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResponse) ProtoMessage()    {}
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b970e5b30bc31cb8, []int{3}
}

func (m *ValidateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResponse.Unmarshal(m, b)
}
func (m *ValidateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResponse.Marshal(b, m, deterministic)
}
func (m *ValidateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResponse.Merge(m, src)
}
func (m *ValidateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResponse.Size(m)
}
func (m *ValidateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResponse proto.InternalMessageInfo

func (m *ValidateTokenResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*CreateTokenRequest)(nil), "authserver.CreateTokenRequest")
	proto.RegisterType((*Token)(nil), "authserver.Token")
	proto.RegisterType((*ValidateTokenRequest)(nil), "authserver.ValidateTokenRequest")
	proto.RegisterType((*ValidateTokenResponse)(nil), "authserver.ValidateTokenResponse")
}

func init() { proto.RegisterFile("pkg/authserver/authserver.proto", fileDescriptor_b970e5b30bc31cb8) }

var fileDescriptor_b970e5b30bc31cb8 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x49, 0xb5, 0xd2, 0x8e, 0x8a, 0x74, 0x88, 0x18, 0xe2, 0x57, 0xdd, 0x93, 0x14, 0xed,
	0xa2, 0xde, 0x7a, 0x13, 0x2f, 0x9e, 0x83, 0x78, 0x12, 0x64, 0xa5, 0x4b, 0x1a, 0x5a, 0x33, 0x71,
	0x67, 0x13, 0xef, 0xbe, 0x82, 0x8f, 0xe6, 0xc9, 0xbb, 0x0f, 0x22, 0xbb, 0x29, 0x35, 0xd6, 0xe2,
	0x6d, 0x66, 0xfe, 0xbf, 0x9d, 0x8f, 0xff, 0xc2, 0x71, 0x31, 0x4d, 0xa5, 0x2a, 0xed, 0x84, 0xb5,
	0xa9, 0xb4, 0x69, 0x84, 0xc3, 0xc2, 0x90, 0x25, 0x84, 0x9f, 0x4a, 0x7c, 0x90, 0x12, 0xa5, 0x33,
	0x2d, 0x55, 0x91, 0x49, 0x95, 0xe7, 0x64, 0x95, 0xcd, 0x28, 0xe7, 0x9a, 0x14, 0x0a, 0xf0, 0xc6,
	0x68, 0x65, 0xf5, 0x1d, 0x4d, 0x75, 0x9e, 0xe8, 0x97, 0x52, 0xb3, 0x45, 0x84, 0xf5, 0x92, 0xb5,
	0x89, 0x82, 0x7e, 0x70, 0xda, 0x4d, 0x7c, 0x8c, 0x31, 0x74, 0x0a, 0xc5, 0xfc, 0x4a, 0x66, 0x1c,
	0xb5, 0x7c, 0x7d, 0x91, 0xe3, 0x3e, 0x74, 0xc9, 0x64, 0xe9, 0xe3, 0x84, 0xd8, 0x46, 0x6b, 0xb5,
	0xe8, 0x0a, 0xb7, 0xc4, 0x56, 0x1c, 0x42, 0xdb, 0x37, 0xc7, 0x10, 0xda, 0xd6, 0x05, 0xf3, 0xb6,
	0x75, 0x22, 0xce, 0x20, 0xbc, 0x57, 0xb3, 0x6c, 0xbc, 0xbc, 0xc3, 0x6a, 0xfa, 0x1c, 0x76, 0x97,
	0x68, 0x2e, 0x28, 0x67, 0xed, 0xf0, 0xca, 0x09, 0x1e, 0xef, 0x24, 0x75, 0x72, 0xf9, 0x19, 0x00,
	0x5c, 0x2f, 0xbc, 0xc0, 0x07, 0xd8, 0x6c, 0x5c, 0x8b, 0x47, 0xc3, 0x86, 0x73, 0x7f, 0x6d, 0x88,
	0x7b, 0x4d, 0xdd, 0x2b, 0x22, 0x7e, 0xfb, 0xf8, 0x7a, 0x6f, 0x85, 0x62, 0x47, 0x56, 0x17, 0x92,
	0x9c, 0x2c, 0xfd, 0x62, 0xa3, 0x60, 0x80, 0xcf, 0xb0, 0xfd, 0x6b, 0x37, 0xec, 0x37, 0xdf, 0xaf,
	0x3a, 0x32, 0x3e, 0xf9, 0x87, 0xa8, 0x0f, 0x13, 0x7b, 0x7e, 0x62, 0x4f, 0x6c, 0xb9, 0x89, 0xd5,
	0x1c, 0x19, 0x05, 0x83, 0xa7, 0x0d, 0xff, 0x83, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x37,
	0x58, 0xf0, 0xcc, 0x0e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthserverClient is the client API for Authserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthserverClient interface {
	// CreateToken creates and returns new JWT token for requested identity.
	CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*Token, error)
	// ValidateToken validates given token and returns its validity.
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type authserverClient struct {
	cc *grpc.ClientConn
}

func NewAuthserverClient(cc *grpc.ClientConn) AuthserverClient {
	return &authserverClient{cc}
}

func (c *authserverClient) CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/authserver.Authserver/CreateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authserverClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, "/authserver.Authserver/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthserverServer is the server API for Authserver service.
type AuthserverServer interface {
	// CreateToken creates and returns new JWT token for requested identity.
	CreateToken(context.Context, *CreateTokenRequest) (*Token, error)
	// ValidateToken validates given token and returns its validity.
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
}

func RegisterAuthserverServer(s *grpc.Server, srv AuthserverServer) {
	s.RegisterService(&_Authserver_serviceDesc, srv)
}

func _Authserver_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthserverServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authserver.Authserver/CreateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthserverServer).CreateToken(ctx, req.(*CreateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authserver_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthserverServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authserver.Authserver/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthserverServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authserver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authserver.Authserver",
	HandlerType: (*AuthserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateToken",
			Handler:    _Authserver_CreateToken_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _Authserver_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/authserver/authserver.proto",
}
